# Generated by Django 4.2.3 on 2023-07-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post2tag', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.AddField(
            model_name='posttag',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag2post', to='posts.tag'),
        ),
    ]
